### ISSUE TITLE
Anyway to get the <style>s to be inline so the server render prevents FOUC on first load?

### ISSUE THREAD

**Issue by rw3iss** [egoist/vue-isomorphic-starter#10]
On first load obviously there is a large FOUC issue with this solution. Is it possible to tell the vue-loader to keep the styles inline or within the template/initial page load for components?

**Comment by egoist** [comment]
use  extract-text-webpack-plugin

**Comment by rw3iss** [comment]
So use extract-text-webpack-plugin to pull all the inline <style></style> sections from the .vue files, put them in their own .css bundles (or one/many bundles), and then load that file in the head before the Vue application scripts?

**Comment by egoist** [comment]
Yeah, that's a common solution to SPA too.

**Comment by rw3iss** [comment]
Okay thanks, will give it a shot :-)

**Comment by egoist** [comment]
With new improvements in vue-server-renderer, this issues is fixed, check out vue-hackernew-2.0 for reference.
