### ISSUE TITLE
example link not working

### ISSUE THREAD

**Issue by sotaan** [egoist/vue-isomorphic-starter#5]
Console error:
![image](https://cloud.githubusercontent.com/assets/9435918/17593850/90bcb960-5fe7-11e6-8506-c39737f68e20.png)
_bundle.js_ output:
![image](https://cloud.githubusercontent.com/assets/9435918/17593857/960fb3ea-5fe7-11e6-9bf9-36cb983d6c37.png)

**Comment by egoist** [comment]
yep, i noticed it too, will fix it on the weekend.

**Comment by mclouvem** [comment]
Hi @egoist, this boilerplate seems great, I'm new to vue and when I try to run your sample, I get an error: ` Cannot find element: #app`
How can I fix it and get the demo running? Also is there a plan to integrate this PR [#4](https://github.com/egoist/vue-isomorphic-starter/pull/4)?

**Comment by APPLLEJN** [comment]
@egoist Did you fix the bug?

**Comment by egoist** [comment]
I'm not going to maintain this project as it got a [new reusable successor](https://github.com/egoist/unvue#prefetch).
