### ISSUE TITLE
Cannot resolve 'file' or 'directory' webkpack assets

### ISSUE THREAD

**Issue by nicgutierrez** [egoist/vue-isomorphic-starter#6]
Hi there

I'm getting the following error after running 'npm run dev' 

    ERROR in ./server/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../build/webpack-assets in /Applications/MAMP/htdocs/insegreto/iso/server @ ./server/index.js 37:21-55

**Comment by egoist** [comment]
Try running `npm run build:client`before than

**Comment by nicgutierrez** [comment]
Thanks @egoist , that fixed the problem.
My local copy now has the same issue of your online demo: js and css 

/static/main.bc1df980fc5e7d5bf29209fb7730e827.css and /static/bundle.909a05244e309f490073.js not found.

Thanks :)
