### ISSUE TITLE
not work in latest node version

### ISSUE THREAD

**Issue by qianhuang** [egoist/vue-isomorphic-starter#7]
I try it in windows. It works well with node 6.4. But I cannot load a page in browser after I upgrade to node 6.5 or latest 6.6.

**Comment by egoist** [comment]
What error occurs?

**Comment by qianhuang** [comment]
No matter in edge, chrome or firefox, the browser keeps loading. The page is visible, but not in correct style. And at this time, if I try to have a look at the source of the page, it is blank. After a long time, after the browser is no long in loading, if I press F12 in chrome, there will be an error “net::ERR_INCOMPLETE_CHUNKED_ENCODING”showed in it.

 

I met this problem on my win 10 laptop. I notice it works well on other computer, so I compare the versions of the node.js installed on them. I found, when I roll back the node.js version to 6.4.0 on my laptop, the problem gone.

**Comment by ncwhale** [comment]
Verified when use node v6.5.0 and v6.6.0, this project does not work.

Works with v6.4.0.

OS: Mint linux 18.

**Comment by egoist** [comment]
Pretty sure it's introduced by https://github.com/egoist/vue-isomorphic-starter/commit/e34ea6e0f99d714fdd341b42677af48e3973db41 , it works after `git reset --hard 47b9b376f7dd93ffec`, I would try to fix it, maybe @LucasIcarus can help 😆

**Comment by LucasIcarus** [comment]
@qianhuang 
@ncwhale       replace the render-stream style resolve the bug.. tested in node 6.6.0 windows 10

@egoist do u mind give me an access for this repo?

**Comment by egoist** [comment]
@LucasIcarus I've added you the the collaborators, cheers 🍻

**Comment by egoist** [comment]
Closed by https://github.com/egoist/vue-isomorphic-starter/pull/8
